# Generated by Django 3.2.5 on 2021-07-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cats'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='cash',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
