# Generated by Django 3.2.5 on 2021-07-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cats_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cats',
            name='cash',
        ),
    ]
